# App Engine configuration (alternative deployment option)
runtime: python39

env_variables:
  # Cloud SQL connection (using Cloud SQL Connector)
  CLOUDSQL_INSTANCE_CONNECTION_NAME: "project:region:instance"
  CLOUDSQL_USER: "your-username"
  CLOUDSQL_PASSWORD: "your-password"
  CLOUDSQL_DATABASE: "lunareading"
  # Note: Set OPENAI_API_KEY and JWT_SECRET_KEY in App Engine settings
  # or use Secret Manager

handlers:
- url: /.*
  script: auto

# Note: For production, set Cloud SQL connection variables above

